export type PreCadastro = {
  id: string
  nome: string
  cpf: string
  email: string
  whatsapp: string
  cidade: string
  uf: string
  situacao_profissional: string
  area_atuacao: string
  empresa?: string
  tempo_atuacao: string
  segmento: string
  regioes: string[]
  formas_participacao: string[]
  canal_contato: string
  status_aprovacao?: string
  indicou_amigo?: boolean
  created_at: string
  licenca?: string
  beneficios_interesse?: string[]
  interesse_convenios?: boolean
  interesse_seguros?: boolean
  interesse_capacitacao?: boolean
  interesse_representacao?: boolean
  temas_juridicos?: string[]
  prioridade_juridica?: string
  processo_andamento?: string
  status_caso?: string
  temas_previdenciarios?: string[]
  pedido_inss?: string
  resumo_necessidade?: string
  documentacao_organizada?: string
  melhor_horario_contato?: string
  expectativa_principal?: string
  comentario_adicional?: string
  lgpd_privacidade?: boolean
  lgpd_tratamento?: boolean
  lgpd_marketing?: boolean
  lgpd_veracidade?: boolean
}
